



default: &default
adapter: redis
url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  adapter: redis
  url: <%= ENV['REDIS_PROVIDER'] %>
  channel_prefix: iamworkingon_b_production



